# Generated by Django 3.1 on 2020-08-14 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileaccess_author', to=settings.AUTH_USER_MODEL)),
                ('profile_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileaccess_who_its_about', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
